---
preset: extended

releaseTypes:
  enabled:
    - mainline
  items:
    mainline:
      collapseVersions: true
      collapsedVersionQualifier: rc
substitutions:
  enabled:
    - node_version
    - cargo_version
