version: '3.8'
services:
  localstack:
    image: localstack/localstack:2.2.0
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack API Gateway
    environment:
      - SERVICES=ssm,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - HOSTNAME=localhost
      - USE_SSL=true
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
