services:
  localstack:
    image: localstack/localstack:3.6
    container_name: localstack
    ports:
      - '4566:4566' # LocalStack API Gateway
      - '4592:4592' # AWS STS port
    environment:
      - SERVICES=ssm,secretsmanager,iam,sts
      - DEBUG=1
      - PERSISTENCE=1
      - LS_LOG=info
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './init-aws.py:/etc/localstack/init/ready.d/init-aws.py'  # ready hook
