import './globals.css';
import type { Metadata } from 'next';
import React, { ReactNode } from 'react';
import Sidebar from '@/sections/dashboard/components/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen bg-background'>
          <Sidebar />
          <main className='flex-1'>{children}</main>
        </div>
      </body>
    </html>
  );
}
