import '../styles/globals.css';
import type {Metadata} from 'next'
import React, {ReactNode} from "react";
import SidebarMenu from "@/components/SidebarMenu";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
    children: ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
    <body>
    <div className="flex bg-gray-800 min-h-screen">
        <SidebarMenu/>
        <main className="flex-1">{children}</main>
    </div>
    </body>
    </html>
  )
}
