name: Backend Quality Assurance Checks

on:
  push:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/backend_qa.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/backend_qa.yml'
    branches:
      - master

defaults:
  run:
    working-directory: src-tauri

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Run Rustfmt
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Install Tauri dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest
          use-tool-cache: true

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --implicit-test-threads
