name: Backend Quality Assurance Checks

on:
  push:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/backend_qa.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/backend_qa.yml'
    branches:
      - master

defaults:
  run:
    working-directory: src-tauri

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Build Code
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --manifest-path=src-tauri/Cargo.toml

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1 --manifest-path src-tauri/Cargo.toml'
          out-type: 'Stdout'

      - name: Run Rustfmt
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings