name: Backend Quality Assurance Checks

on:
  push:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/backend_qa.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/backend_qa.yml'
    branches:
      - master

defaults:
  run:
    working-directory: src-tauri

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin -- --test-threads 1 --manifest-path 'src-tauri/Cargo.toml' --fail-under 90 --out Stdout

      - name: Run Rustfmt
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings